### ISSUE TITLE
Project longitude and latitude not saved by the assistant

### ISSUE THREAD

**Issue by KnightEther** [burgercode/TheGramginers#172]

**Comment by jrossett** [comment]
Can you explain a bit more this bug?

**Comment by KnightEther** [comment]
I don't have the details, the problem is that when we save a project, the longitude and the latitude is not in the database.
I'll fix it next week

**Comment by jrossett** [comment]
I can try it now, when you say save it is in the edit part? creation?

**Comment by KnightEther** [comment]
I've seen it for creation, it may be the case of the edition as well since it is the same code.
I plan to work on the map next week and more precisely on the search according to latitude and longitude so it will be easier for me to fix this bug in this context I think.
